project:
  type: website
  output-dir: ../public

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

quartodoc:
  # the name used to import the package
  package: quartodoc

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - get_object
        - preview